### ISSUE TITLE
How to reproduce the result in the paper?

### ISSUE THREAD

**Issue by muhoushaonian** [Haiyao-Nero/InvariantStock#1]
Your article is very engaging. How can I reproduce the results you achieved in the Chinese stock market? I found that the IC and RankIC performance are not good in the dataset I constructed using 128 factors for the CSI 300.

**Comment by Haiyao-Nero** [comment]
The dataset used in this study was collected using Tushare. To reproduce the results, you will need to gather the data independently, as it is not a public dataset. However, we have included some sample data in this repository. Details of the stock features are provided in Tables 1 and 5.

**Comment by muhoushaonian** [comment]
Thanks for your reply. By the way, I' curious about the difference between _features dimension_ and _number of factors_ in args setting. For example, you select 26 features for China Stock Market, how to set these two args?

**Comment by Haiyao-Nero** [comment]
Since the predictor is a typical FactorVAE structure, the factors are the output of the FactorVAE's encoder.

**Comment by muhoushaonian** [comment]
Thanks for your reply.
